using HeartCentreW104.Helpers;

using NerveCentreW10.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NerveCentreW10.ViewModels
{
    public class Section2ViewModel
    {
        public ObservableCollection<SubsectionModel> SubsectionList { get; } = new ObservableCollection<SubsectionModel>();

        public Section2ViewModel()
        {
            CloudClass cloudclass = new CloudClass();

            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section21",
                Title = "2.1. Overview: Brain",
                Subtitle1 = "Overview of the Brain",
                Description1 = "The human nervous system can be classified in one of two ways: structurally or functionally.<br/><br/>Structurally, the nervous system can be divided into the central nervous system (CNS) and the peripheral nervous system (PNS). The CNS consists of the brain, spinal cord and retina, and it’s responsible for most of the ‘processing’ of the nervous system. The PNS consists of the twelve pairs of cranial nerves and the 31 pairs of spinal nerves. Sometimes, the enteric nervous system (i.e. the independent nerve network of the gastrointestinal tract) is also classified as part of the PNS.<br/><br/>Functionally, the nervous system can be divided into the somatic nervous system (SNS) and the autonomic nervous system (ANS). The SNS is under voluntary control and has sensory and motor components. For example, the motor nerves allow the muscles in the hands and fingers to contract when we want to type on a PC, and the sensory nerves allow us to feel the pressure and texture of the keys on the keyboard when we type. The ANS is involuntary and ensures that peripheral blood vessels constrict (‘vasoconstriction’) when we are cold, sweat is produced when we are hot, adrenaline is secreted in times of stress and our pupils constrict in bright light.<br/><br/>In this section, we will be focusing on the structural divisions of the nervous system, specifically the CNS.",
                Subtitle2 = "Welcome to the Brain: the Hindbrain and Midbrain",
                Description2 = "The brain is a wonderful but complex organ that affects, in some way, almost every aspect of our experience. Before we look at its function, let’s get an understanding of its structure.<br/><br/>The brain can be divided into three main areas (see Figure 2.1.1. and Figure 2.1.2.) based on its development in the embryo and These are the:<br/><br/><b>1. Hindbrain</b><br/>The hindbrain lies caudally in the brain overall and it consists of three structures: the medulla oblongata, the pons and the cerebellum. The medulla and pons, in combination with the midbrain, are referred to jointly as the brainstem. The brainstem is integral to our survival because it contains vital cardiac and respiratory centres that in part determine are heart rate and breathing rate. A loss in any activity in the brainstem due to illness or injury is extremely dangerous. The cerebellum, which is also a hindbrain structure, allows us to perform repeated, stereotypical activities, such as walking, and maintains our coordination and balance. Take a look at the two figures on this page and see if you can identify the medulla, pons and cerebellum.<br/><br/><b>2. Midbrain</b><br/>As mentioned above, the midbrain is part of the brainstem. Like the cerebellum, it helps us to walk. The midbrain is also involved in the processing of eye reflexes, such as the pupillary light reflex (i.e. both your pupils constrict in bright light).",
                Subtitle3 = "Welcome to the Brain: the Forebrain",
                Description3 = "<b>3. Forebrain</b><br/>The forebrain is well-developed in human compared to other mammals and has four main parts. First is the cerebral cortex. This is the outer layer of grey matter surrounding the cerebrum. The cerebral cortex is divided into hemispheres (left and right) and then subdivided into four distinct areas, or lobes. These are called the frontal lobe, temporal lobe, occipital lobe and parietal area (why it’s called the parietal area, not lobe, I don’t know, it's an anatomical thing!) The cerebral cortex is a higher processing centre and, as such, it allows us to process and understand lots of sensations (e.g. pain, temperature, pressure), process and enact complex motor activities (such as the intricate finger work involved in painting) and understanding what we see in our visual field. See if you can identify these structures in the accompanying figures.<br/><br/>The second part of the forebrain includes subcortical structures, such as the basal ganglia, which is involved in controlling voluntary movements and inhibiting excess and unwanted movements. Note that the hippocampus and amygdala, although they appear subcortical, are actually folds of the cerebral cortex. The hippocampus is involved in the formation of memories and the amygdala is involved in regulating instinctive behaviours, such as hunger, fear, anger and sexual arousal.<br/><br/>The third part of the forebrain includes the large bundles of fibres that connect the two halves of the cerebrum. The largest bundle of fibres is called the corpus callosum, and it can be seen in Figure 2.1.2.<br/><br/>The fourth part of the forebrain is the diencephalon, which consists of the thalamus and hypothalamus. The thalamus is a major relay centre, connecting the brainstem with the cerebrum. The hypothalamus is home to the pituitary gland, and it is involved in the regulation of lots of nervous and endocrine responses, such as managing our temperature, sleep-wake cycles, thyroid hormones and the menstrual cycle. You can see the approximate location of the thalamus and hypothalamus in Figure 2.1.2.",
                ImageUri1 = "brainlateral.png",
                ImageUri2 = "brainmedial.png",

                Popup1Title = "Clinical Note: Brain Damage",
                Popup1Content = "As you can probably guess, the extent of disability after brain damage is dependent on where exactly the brain is injured. For example, a traumatic blow to the back of the head could damage the cerebellum and brainstem – if the cardiac and respiratory centres stop working, the person’s heart and lungs will stop working. This is referred to as ‘brainstem death’. Take another example: damage to the hippocampus in Alzheimer’s disease can lead to memory problems (see Section 4.1. Alzheimer’s Disease).",
                Popup2Title = "Research Note: Homunculus",
                Popup2Content = "Search the web for 'sensory homunculus' and you will see images of a funny-looking man with a big head and big hands. The size of the man's body parts indicate how much of the brain is dedicated to detecting and processing sensations from that body part. For example, big hands mean the hands are very sensitive, as the brain dedicates a lot of cortex to processing sensations from here.",
                Popup3Title = "Revision Note: Love Diagrams!",
                Popup3Content = "There’s a lot to remember here, but don’t panic. Try and sketch out a rough outline of the brain and label it without looking at the notes. Use coloured pens to differentiate between the brain regions if this helps. Doing this again and again is a great way to test your general brain anatomy before an exam.",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section22",
                Title = "2.2. Overview: Spinal Cord",
                Subtitle1 = "Overview of the Spinal Cord",
                Description1 = "The spinal cord is the second component of the CNS and is a highly organised tube protected by the bones of the vertebral column. The spinal cord is continuous with the medulla, the most inferior (or “caudal”) part of the brainstem. You can see this in Figure 2.2.1. The spinal cord role is to allow the brain to receive sensory information from and send motor information to almost every region of the body. However, the spinal cord is also responsible for some basic processing of action potentials – this is performed by interneurons (see Section 1.5. Reflex Arcs).",
                Subtitle2 = "Divisions of the Spinal Cord",
                Description2 = "The spinal cord, like the vertebral column, can be grouped into five distinct structural divisions. Starting at the medulla and moving inferiorly, these are the cervical, thoracic, lumbar, sacral and coccygeal divisions. When looking at the spinal cord as a whole, there are some important features to note. Each of the five spinal divisions contains a number of spinal segments. Each spinal segment gives off a pair of spinal nerves at that level (one to the left side of the body and one to the right side). In total, there are 31 pairs of spinal segments and therefore 31 pairs of spinal nerves. You can read more about spinal nerves in Section 3.1. Spinal Nerves. Now take a look at Figure 2.2.1. and note that the…<br/><ul><li><b>Cervical division has 8 spinal segments and gives off 8 pairs of spinal nerves.</b></li><li><b>Thoracic division has 12 spinal segments and gives off 12 pairs of spinal nerves.</b></li><li><b>Lumbar division has 5 spinal segments and gives off 5 pairs of spinal nerves.</b></li><li><b>Sacral division has 5 spinal segments and gives off 5 pairs of spinal nerves.</b></li><li><b>Coccygeal division has 1 spinal segment and gives off 1 pair of spinal nerves.</b></li></ul><br/>The familiar tube-like appearance of the spinal cord, referred to here as the ‘spinal cord proper’, only exists from C1 – L1/L2. Below L1/L2, the spinal cord proper tapers off to become the conus medullaris, but the spinal nerves do continue downwards in the vertebral column in what looks like a horse’s tail. This bunch of spinal nerves is therefore called the cauda equina.",
                Subtitle3 = "Contents of the Spinal Cord",
                Description3 = "As mentioned before, the spinal cord is a major relay centre between the peripheral nerves and the brain. As such, a large proportion of the spinal cord contains ascending, sensory nerve fibres (running to the brain) and descending, motor nerve fibres (running to skeletal muscles, smooth muscle and glands in the periphery). Nerve fibres responsible for the same or similar functions are grouped together into ‘tracts’ in the spinal cord. For example, the ascending, sensory nerve fibres that carry the sensation of pain and temperature from the skin to the brain are all found in the spinothalamic tract.<br/><br/>Figure 2.2.2. shows the main tracts of nerve fibres and their locations in a transverse cross-section of the spinal cord. These tracts and their roles are noted below too. As you can see, the name of the tracts has two parts; the first part is where the tract is coming from, the second part is where the tract is heading to.<br/><br/>The main ascending, sensory tracts are:<br/><br/><ul><li><b>Dorsal column medial lemniscus (DCML) tract</b> – carries fine touch and proprioception signals to the brain. (Note that proprioception is our sense of knowing where our body is in 3D space, e.g. when we hold our left arm out horizontally, we know its position relative to the rest of the body.)</li><li><b>Spinothalamic tract</b> – carries pain and temperature signals to the brain.</li><li><b>Spinocerebellar tract</b> – carries proprioception signals to the brain.</li></ul><br/>The main descending, motor tracts are:<br/><br/><ul><li><b>Corticospinal tracts</b> – carry motor information that allows the conscious control of skeletal muscles.</li><li><b>Subconscious motor tracts</b> – involved in the subconscious monitoring of motor activity and making adjustments as necessary. Although I have called these tracts subconscious motor tracts, they do have specific names and functions...(1) Vestibulospinal tracts - vestibular nuclei of pons and medulla > spinal cord (for stabilising head movements and posture); (2) Reticulospinal tracts - reticular formation of pons and medulla > spinal cord (for balance and excitation of respiratory muscles); (3) Rubrospinal tract - red nucleus of midbrain > spinal cord (for exciting flexors of the upper limb); (4) Tectospinal tract - superior colliculus of midbrain > cervical region of spinal cord (for head and neck movements linked to sight).</li></ul>",
                ImageUri1 = "spinalregions.png",
                ImageUri2 = "spinalcross.png",

                Popup1Title = "Clinical Note: Cord Transection",
                Popup1Content = "If the spinal cord is completely severed horizontally, it is known as a complete cord transection. This could occur in a car crash where there is sudden deceleration. All of the spinal tracts are severed, resulting in complete paralysis from the level of the injury and downwards. For example, a complete cord transection at T10 would mean that a person would lose sensory and motor function in both legs, but they would retain sensory and motor function in their arms. The higher the transection, the more severe the paralsysis.",
                Popup2Title = "Research Note: Need More Detail?",
                Popup2Content = "The tracts mentioned in this page have been grouped to simplify understanding. However, there are multiple named tracts within each group. For example, within the DCML tracts, there is the gracile fasciculus and cuneate fasciculus. The gracile fasciculus carries proprioception and fine touch signals from Co1 up to T7, while the cuneate fasciculus carries proprioception and fine touch signals from T6 up to C1. If you need to know all of these tracts, check out the References in Section 8.0. More Resources for some useful links.",
                Popup3Title = "Revision Note: Spinal Segments",
                Popup3Content = "It’s important to realise the mismatch of the lengths of the spinal cord proper and their associated spinal segment. Here it is in simple terms:<br/><ul><li>Every spinal segment has two associated spinal nerves.</li><li>Spinal segments do not always lie at the associated vertebral level.</li><li>The spinal segments T11 to Co1 are squashed together at the end of the spinal cord.</li><li>All spinal nerves leave the vertebral canal at their associated vertebral level.</li><li>For example, the spinal segment S2 lies at L1, but the S2 spinal nerves branch off here, run downwards in the cauda equina, and then leave at the S2 vertebral level.</li></ul><br/>",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section23",
                Title = "2.3. Blood Supply",
                Subtitle1 = "Blood Supply to the CNS",
                Description1 = "The brain and spinal cord require a constant supply of oxygen- and glucose-rich blood at a constant pressure in order to function properly. In the healthy human, the brain and spinal cord have certain protective features that ensure this is always the case. Without oxygen, irreversible brain damage can occur within five minutes.",
                Subtitle2 = "Blood Supply to the Brain",
                Description2 = "The brain has a dual blood supply. This means it is supplied by two pairs of arteries. These arteries are the <b>left and right internal carotid arteries and the left and right vertebral arteries.</b><br/><br/>The left and right internal carotid arteries are branches of the common carotid artery (this is the artery in your neck that you press on when taking your pulse). The internal carotid artery enters the skull through a canal and provides much of the blood supply to the front and middle portions of the brain. When in the skull, the internal carotid divides into the anterior cerebral artery, the middle cerebral artery and the posterior communicating artery.<br/><br/>The left and right vertebral arteries are branches of the subclavian artery on each side. These arteries enter the skull through the foramen magnum (the large hole in the base of the skull through which the spinal cord connects to the medulla). The left and right vertebral arteries then join up to form the basilar artery. The basilar artery then divides again to form the posterior cerebral arteries.<br/><br/>Together, the branches of the internal carotid arteries and the vertebral arteries supply the entire brain with blood. At the base of the brain, all of these arterial branches actually link together, forming an arterial ring (or ‘anastomosis’) called the circle of Willis. This arterial circle, in theory, provides an emergency blood supply when required; if one branch gets blocked, the other branches that contribute to the arterial circle will compensate for it. Figure 2.3.1. shows the circle of Willis and other important arteries. Note that the circle of Willis consists of the:<br/><ul><li><b>2x Anterior cerebral arteries</b></li><li><b>1x Anterior communicating artery</b></li><li><b>2x Internal carotid arteries</b></li><li><b>2x Posterior communicating arteries</b></li><li><b>2x Posterior cerebral arteries</b></li><li><b>1x Basilar artery</b></li></ul><br/>",
                Subtitle3 = "Blood Supply to the Spinal Cord",
                Description3 = "The blood supply to the spinal cord is illustrated in Figure 2.3.2. The anterior spinal artery runs along the anterior aspect of the spinal cord, just in front of the ventral median fissure. It gives off branches that supply much of the grey matter in the spinal cord. There are also two posterior spinal arteries, one on each side, and these give off branches that supply the posterior aspect of the spinal cord (in particular, the DCML tracts, that we identified in Section 2.2. Overview of the Spinal Cord).<br/><br/>Overall, these three spinal arteries can’t provide enough blood for the entire spinal cord, so the intercostal arteries and lumbar arteries also help out by supplying segmental arteries. These segmental arteries give off anterior and posterior radicular arteries, which supply that extra little bit of required blood to the spinal cord. The radicular arteries also give off smaller arteries that run around the outside of the spinal cord, forming an anastomotic network called the vasocorona.",
                ImageUri1 = "brainblood.png",
                ImageUri2 = "spinalblood.png",

                Popup1Title = "Clinical Note: PCA Blockage",
                Popup1Content = "A blockage of the posterior cerebral artery with a blood clot can lead to severe nervous system deficits. The posterior cerebral artery supplies two key structures: the hippocampus and the primary visual cortex. The hippocampus is required for forming memories and the primary visual cortex is required for understanding images from the retina (see Section 2.1. Overview of the Brain). As such, a blockage in the posterior cerebral artery which is not treated quickly can lead to memory and visual problems. Structure, function and disease pathology are intricately linked.",
                Popup2Title = "Research Note: Variations",
                Popup2Content = @"Click <a href=""http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3982101/"">here</a> to take a look at an interesting article about the function of the circle of Willis, written by Vrselja et al. (2014). The authors hypothesise that the circle of Willis absorbs the pressure of the blood entering the brain, thereby preventing damage to the smaller cerebral blood vessels and the blood brain barrier.",
                Popup3Title = "Revision Note: Practical Exams",
                Popup3Content = "If you have a practical exam where you might have to identify the circle of Willis on a 3D model or prosection, now is a good time to get a model, sit down and appreciate the angle at which the circle of Willis lies, as it isn’t really clear when you look at a 2D diagram. Appreciate that the circle of Willis lies fairly horizontally, while the vertebral and basilar arteries ascend at an angle along the surface of the medulla and pons to join the circle of Willis. This is a good exam question, so know your stuff!",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section24",
                Title = "2.4. The Meninges",
                Subtitle1 = "Overview of the Meninges",
                Description1 = "The meninges are three protective membranes that line the brain and spinal cord. The meninges, along with cerebrospinal fluid (CSF), act as shock absorbers in scenarios when the head is moved suddenly in a particular direction. They also provide a safe environment for the passage of blood vessels and space for CSF to move through.",
                Subtitle2 = "The Meningeal Layers",
                Description2 = "There are three main meningeal layers, which are described below and shown in Figure 2.4.1.<br/><br/><b>1. Dura mater</b><br/>The dura mater is the outermost and toughest layer of the meninges. ‘Dura mater’ is actually a Latin phrase that translates as ‘hard mother of the brain’. The dura mater, which is sometimes just called the dura, is divided into two sub-layers: the outer endosteal layer and the inner meningeal layer. The endosteal layer is firmly attached to the cranium (skull). However, the meningeal layer drops downwards in the midline, forming a meningeal fold called the falx cerebri. The falx cerebri separates the left and right cerebral hemispheres. Another similar fold of the meningeal layer lies between the cerebrum and the cerebellum, and this is called the tentorium cerebelli. Both of these dural folds provide room for the passage of particular veins in the brain, called the dural venous sinuses, which help to drain blood from the brain into the internal jugular veins.<br/><br/><b>2. Arachnoid mater</b><br/>The arachnoid mater is the thin middle layer of the meninges. It is attached to the meningeal layer of the dura mater and follows its folds. In Latin, the arachnoid and pia mater are known as the ‘leptomeninges’, which translates as ‘thin membranes’.<br/><br/><b>3. Pia mater</b><br/>The pia mater is the thin innermost layer of the meninges that is intimately adhered to the folds of the brain matter.<br/><br/>It’s important to note that the meninges extend to cover the spinal cord too. In fact, the meninges of the brain are continuous with the meninges of the spinal cord through the foramen magnum of the skull. Although the spinal cord proper ends at L1/L2, the meninges, in one form or another, extend to the level of the S2 vertebra.",
                Subtitle3 = "The Meningeal Spaces",
                Description3 = "As you might expect, there are a number of spaces associated with the three main meningeal layers. These are detailed below and in Figure 2.4.2.<br/><br/><b>1. Extradural (also called epidural) space</b><br/>This space is found above the endosteal dura layer, i.e. it is found between the endosteal dura layer and the skull. The extradural space is a potential space - this means that it normally isn't occupied by anything at all but in the event of, for example, a bleed from the arteries supplying the meninges, blood can accumulate in it – this is called an extradural haematoma.<br/><br/><b>2. Subdural space</b><br/>The subdural space lies between the arachnoid mater and dura mater. This is another potential space that has little ‘give’ if blood leaks into it – this would be called a subdural haematoma.<br/><br/><b>3. Subarachnoid space</b><br/>The subarachnoid space is located between the arachnoid space and the pia mater. It is an actual space that is filled with moving CSF, as well as a variety of blood vessels that will eventually pierce the pia mater and supply the brain matter.<br/><br/>Note that the pia mater is so intimately adhered to the brain matter and all of ridges and dips that there is no subpial space.",
                ImageUri1 = "meningeallayers.png",
                ImageUri2 = "meningealspaces.png",

                Popup1Title = "Clinical Note: Herniation",
                Popup1Content = "The skull is a rigid box with the meninges inside. If there is a severe, ongoing bleed into one of the meningeal spaces, it could lead to a life-threatening condition called herniation. This occurs when a haematoma (collection of blood) gets so large that it pushes the brainstem downwards and through the foramen magnum. This has profound effects on an individual’s basic survival functions. It also leads to very abnormal movements in what is called ‘posturing’.",
                Popup2Title = "Research Note: Meningitis",
                Popup2Content = @"Meningitis is life-threatening inflammation of the meninges by a bacteria or virus. It can spread to the blood too, causing meningococcal septicaemia. <a href=""http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3131058/"">This</a> article from Clinical Microbiology Reviews describes the pathogenesis (disease origins) and pathophysiology (disease mechanisms) of meningitis, as well as the molecular basis for various treatments.",
                Popup3Title = "Clinical Note 2: Spinal Tap",
                Popup3Content = "A spinal tap (also called lumbar puncture) is a delicate procedure performed when a person has suspected meningitis. It is only possible because of the presence of the lumbar cistern – this is the name for the large portion of subarachnoid space below the spinal cord. It is filled with CSF, of which a sample can be taken by inserting a needle in-between the vertebral arches of L3/L4 in an adult or L4/L5 in a child, using bumps on the posterior aspect of the pelvis as a guide for finding these vertebral levels. Remember the spinal cord proper ends at L1/L2, and from this point to S2 the cauda equina exists bathed in CSF. As such, the cauda equina (see Section 2.2. Overview of the Spinal Cord) does lie in the lumbar cistern but it is bathed in CSF and is unlikely to be damaged by the blunt needle.",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section25",
                Title = "2.5. Glial Cells",
                Subtitle1 = "Overview of Glial Cells",
                Description1 = "Glial cells are support cells in the nervous system. Glial cells are different from neurons because glial cells do not conduct action potentials and they do not synapse with other nearby cells. Instead, they provide structural and protective support for neurons. There are many more glial cells than neurons. In fact, it is estimated that for every 1 neuron there are 10 glial cells. There are five types of glial cell:<ol><li>Astrocytes</li><li>Oligodendrocytes</li><li>Ependymal cells</li><li>Microglia</li><li>Radial glia</li></ol>",
                Subtitle2 = "Astrocytes and Oligodendrocytes",
                Description2 = "<b>Astrocytes</b><br/>These are the most numerous glial cells in the brain. They have lots of functions, so only their main ones will be described here. It was previously thought that astrocytes contributed to the formation and structural stability of the blood-brain barrier (BBB), by extending ‘astrocytic feet’ around the brain capillaries and thereby preventing toxins and unwanted chemicals from entering the delicate brain matter. However, more recent evidence suggests that astrocytes don't make a large contribution to the BBB. Instead they help to control the diameter of blood vessels by allowing them to dilate - this means they help control blood flow to particularly active brain regions. Astrocytes also maintain the health of synapses and regulate ion and neurotransmitter levels (specifically, astrocytes remove excess K+ ions and excess glutamate neurotransmitter).<br/><br/><b>Oligodendrocytes</b><br/>These provide myelination around neurons in the central nervous system, as shown in Figure 2.5.2. Myelination speeds up the transmission of action potentials by making them ‘jump’ along the neuron at specific myelin-free points called nodes of Ranvier. Oligodendrocytes are very similar to Schwann cells in the peripheral nervous system, but the difference is oligodendrocytes myelinate between five and eight neurons, whereas one Schwann cell myelinates only one neuron.",
                Subtitle3 = "Ependymal Cells, Microglia and Radial Glia",
                Description3 = "<b>Ependymal Cells</b><br/>These line the ventricles of the brain and have cilia that help to waft CSF out of the ventricles and around the ventricular system (see Section 2.6.2. CSF and the Ventricles). They also actively secrete Na+ ions which contributes to the formation of CSF.<br/><br/><b>Microglia</b><br/>These are the immune cells of the brain. They are essentially macrophages which ingest and destroy foreign particles and remove parts of damaged neurons. In many situations, they also take part in gliosis and thus migrate to the site of injury in the brain.<br/><br/><b>Radial Glia</b><br/>Radial cells are used during development of the central nervous system. They act as scaffolds for newborn neurons to migrate from the ventricular surface of the brain to the pial surface of the brain, where their final locations will be.",
                ImageUri1 = "astro.png",
                ImageUri2 = "oligo.png",

                Popup1Title = "Clinical Note: Astrocytoma",
                Popup1Content = @"An astrocytoma is a type of glioma – essentially a cancerous brain tumour consisting of mutated glial cells. Astrocytomas can grow throughout the brain and are graded based on their severity, with grade I being the least aggressive and grade IV being the most aggressive and likely to spread to other parts of the brain. In the UK, about 1/3 of all brain tumours and brain cancers are astrocytomas. Read more by visiting <a href=""https://www.thebraintumourcharity.org/understanding-brain-tumours/types-of-brain-tumour-adult/astrocytoma/"">The Brain Tumour Charity website.</a>",
                Popup2Title = "Research Note: Neurogenesis",
                Popup2Content = "It was once thought that neurogenesis – the generation of new neurons and glia – only happened before birth. However, experimental evidence in the 1980s and 1990s showed that this hypothesis was incorrect. There are two areas of the adult brain where neural stem cells reside, namely the subventricular zone and the hippocampus. These adult neural stem cells are capable of eventually differentiating into either mature neurons, oligodendrocytes or astrocytes.",
                Popup3Title = "Revision Note: Body Parts...",
                Popup3Content = "It seems that all the glial cells have their own body parts…could this help you remember their names and functions? Astrocytes have feet (for blood vessels), oligodendrocytes have arms (for myelin-wrapping), ependymal cells have hair (for CSF-wafting), microglia have mouths (for eating debris) and radial glial cells have hands (for giving a helping hand to immature neurons).",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section26",
                Title = "2.6. CSF and the Ventricles",
                Subtitle1 = "CSF and the Ventricles",
                Description1 = "The ventricles are fluid-filled spaces within the brain. There are four ventricles in total. Beginning in the cerebrum and moving inferiorly, the ventricles are called:<br/><ul><li>The two lateral ventricles (one on the left and one on the right)</li><li>The third ventricle</li><li>The fourth ventricle</li></ul><br/>",
                Subtitle2 = "What is CSF?",
                Description2 = "Cerebrospinal fluid, or CSF, is a clear liquid produced by the choroid plexuses that lie within the four ventricles. It flows throughout the ventricular system and subarachnoid space surrounding the brain and spinal cord. Each choroid plexus actively secretes CSF into the ventricular lumens, although the choroid plexuses in the lateral ventricles produce the most CSF. Ependymal cells (see Section 2.5. Glial Cells) are crucial to the functioning of the choroid plexuses – they actively secrete Na+ ions and use their cilia to waft CSF through the ventricular system.<br/><br/>CSF is formed from the filtrates of blood that passes through the choroid plexuses (see Figure 2.6.1.). The composition of CSF is as follows:<br/><br/><ul><li><b>Water</b>, which makes up 99% of CSF</li><li><b>Ions</b>, including Na+, K+, Ca2+, Cl- and Mg2+ ions. There is more Na+, Cl- and Mg2+ in CSF than in blood, but less Ca2+ and K+ than in blood;</li><li><b>Molecules</b>, including glucose and proteins (again, normally present in lower concentrations in CSF compared to blood).</li></ul><br/>There are very few cells present in CSF; in fact, the presence of white blood cells can indicate a serious infection of the meninges. The process of forming CSF is described as 'active' – this is because the secretion of Na+ ions from the ependymal cells requires energy (ATP). As expected, water from the blood naturally follows the Na+ ion movement by osmosis. So, what is the function of CSF? The brain is essentially suspended in CSF and the meningeal layers. As such, these structures act as shock absorbers to the brain when the head moves. They dissipate any kinetic energy from the ‘floating’ brain and thereby prevent damage caused by the brain (and dura) forcefully hitting the skull. CSF is also thought to play a protective role by circulating nutrients filtered from the blood and removing toxins from the CNS.",
                Subtitle3 = "Flow of CSF through the Ventricular System",
                Description3 = "The lateral ventricles are essentially 3D C-shaped spaces that lie within the cerebrum (see Figure 2.6.2.). The lateral ventricles are lined with ependymal that produce and secrete cerebrospinal fluid (CSF) into the centre of the ventricles. The CSF then flows through the interventricular foramina* (again, there is a left foramen and a right foramen). These foramina carry the CSF into the third ventricle, which is sandwiched between the left and right parts of the thalamus. (*By the way, foramina are basically just holes through which the fluid flows!)<br/><br/>CSF then flows downwards from the third ventricle, through a thin tube called the cerebral aqueduct, which leads into the fourth ventricle. The fourth ventricle is situated between the pons and cerebellum, and it’s described as being shaped like a fairly flat tent. The CSF then leaves the fourth ventricle by one of three openings (also called apertures): the two lateral apertures (also called ‘foramina of Luschka’) and the median aperture (‘foramen of Magendie’). It will eventually leave this canal and move into the subarachnoid space surrounding the spinal cord and brain. The production of new CSF in the lateral ventricles is balanced by the absorption of older CSF into the dural venous sinuses at the arachnoid villi (see Figure 2.4.2.).",
                ImageUri1 = "choroid.png",
                ImageUri2 = "brainventricles.png",

                Popup1Title = "Clinical Note: Hydrocephalus",
                Popup1Content = "Hydrocephalus is essentially excess CSF surrounding the brain. The most common reason is a blockage of CSF flow somewhere in the ventricular system. CSF builds up and the ventricles dilate. Hydrocephalus can be present at birth or be acquired during later life, e.g. after a head injury. The pressure increases in the skull and can cause headaches, vomiting and blurry vision.",
                Popup2Title = "Research Note: CSF and MS",
                Popup2Content = @"The National Multiple Sclerosis Society describes how CSF is altered in people living with MS. When examined after a lumbar puncture, CSF will often contain markers that the immune system is attacking itself. These markers include IgG antibodies, oligoclonal bands and occassionally proteins from broken-down myelin. Take a look at the webpage <a href=""http://www.nationalmssociety.org/Symptoms-Diagnosis/Diagnosing-Tools/Cerebrospinal-Fluid-(CSF)"">here</a>.",
                Popup3Title = "Revision Note: 3rd Ventricle",
                Popup3Content = "The third ventricle can be difficult to get your head around, and difficult to see on a diagram and 3D model. So, take another look at Figure 2.1.2 in Section 2.1. Overview of the Brain. This image shows the medial aspect of the brain, drawn from a mid-sagittal view. Although the light blue area is labelled ‘thalamus’, you are actually looking at the thalamus through the exposed third ventricle (remember, the ventricles are just spaces).",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section27",
                Title = "2.7. Cerebral Cortex",
                Subtitle1 = "The Cerebral Cortex",
                Description1 = "The cerebral cortex is the outermost layer of the cerebrum, and it is composed of grey matter. Note that the nervous system is made up of two types of matter: white matter and grey matter. White matter is so-called because it is made up of the myelinated axons of neurons. Grey matter is so-called because it is made up of the non-myelinated cell bodies of neurons.<br/><br/>As already mentioned in Section 2.1. Overview of the Brain, the cerebral cortex is subdivided into hemispheres (right and left) and each hemisphere is then divided into four lobes (frontal lobe, parietal area, occipital lobe and temporal lobe). The cerebral cortex contains many important processing and communication centres. Out of all the primates, humans have the largest cerebral cortex, which reflects our unique cognitive abilities.<br/><br/>The brain has a noticeable appearance with prominent raised folds and grooves. In neuroscience, the raised folds are called gyri, the shallow grooves are called sulci and the deep grooves are called fissures. In some cases, functions of the brain are localised in particular gyri, and you will see this below. Note that, in Figure 2.7.1., the coloured areas represent functional areas (also called functional cortices) and the black lines represent sulci and fissures. Note also that the motor and sensory areas in the left cerebral hemisphere are largely responsible for the motor and sensory functions in the right side of the body and vice versa. This is because the fibres cross over (also called decussate) at various points on the way to the brain.<br/><br/>Now, let’s take a look at the various areas of cerebral cortex and their associated functions that have been identified by researchers, and then look briefly at the white matter tracts that lie beneath the cortex.",
                Subtitle2 = "Grey Matter",
                Description2 = "<b>Primary motor cortex</b><br/>This cortex initiates complex patterns of muscle contractions that we use, for example, to move our arms, hand and fingers when chopping up vegetables for a meal. The primary motor cortex lies directly within the precentral gyrus, which itself lies anterior to the central sulcus. In this cortex a mini map of the body exists so the brain can identify and enable the contraction of a specific muscle of the body.<br/><br/><b>Primary somatosensory cortex</b><br/>This cortex receives and begins to interpret somatic sensory information from the peripheral nervous system, for example, the temperature of the water that we are going to boil the vegetables in. The primary somatosensory cortex lies directly within the postcentral gyrus, which itself lies posterior to the central sulcus. In this cortex a mini map of the body exists so the brain can identify exactly where a sensation comes from.<br/><br/><b>Premotor cortex</b><br/>This cortex is in addition to the primary motor cortex and is thought to help prepare the body for movement and postural changes.<br/><br/><b>Sensory association cortex</b><br/>This cortex is in addition to the primary somatosensory cortex and is also responsible for processing sensations and, in the dominant lobe, helps us to use language to communicate.<br/><br/><b>Prefrontal cortex</b><br/>This cortex allows us to control our behaviour, plan and make decisions, and use our intellectual abilities. Alcohol affects the functioning of the prefrontal cortex, causing people to lose their social inhibitions.<br/><br/><b>Broca's area</b><br/>Broca’s area is found in the dominant hemisphere and is known as the motor speech area. It allows us to choose the correct words and vocalise them.<br/><br/><b>Wernicke's area</b><br/>Wernicke’s area is found in the dominant hemisphere too and is known as the sensory speech area. It allows us to understand words that are spoken to us.<br/><br/><b>Primary auditory cortex</b><br/>This cortex allows us to perceive sounds that are received as action potentials from the cochlea of the inner ear.<br/><br/><b>Primary visual cortex and visual association cortex</b><br/>The primary visual cortex allows us to interpret images. We receive an upside-down image from the retina and this area of the brain flips it the right way around. The visual association cortex allows us to recognise and understand images that were sent from the retina.",
                Subtitle3 = "White Matter",
                Description3 = "The areas of white matter connect different parts of the brain to each other. There are different categories of white matter, which are referred to as tracts:<br/><br/><b>Association tracts</b><br/>These connect different areas of grey matter contained in the same cerebral hemisphere. For example, association fibres link association cortices with the hippocampus (see Section 2.8. Limbic System)<br/><br/><b>Commissural tracts</b><br/>These connect areas of grey matter in one cerebral hemisphere with the same area in the opposite cerebral hemisphere. The largest of these is the corpus callosum, and this can be seen in Figure 2.7.2. It is estimated that it contains 200 million axons. The fibres of the corpus callosum that bend forward to the tips of the frontal lobes are called forceps minor, and the fibres that bend backwards to the tips of the occipital lobe are called forceps major.<br/><br/><b>Projection tracts</b><br/>These connect areas of grey matter in the cerebrum with lower areas of the brain, such as the thalamus and brainstem.",
                ImageUri1 = "cortexcoloured.png",
                ImageUri2 = "corpus.png",

                Popup1Title = "Clinical Note: Aphasia",
                Popup1Content = "As mentioned above, Broca’s area is the motor speech area. If Broca’s area or its communicating neuron tracts are damaged, a patient will struggle to produce language in both speech and writing. They are aware of their inability to produce language and may be frustrated at this. This is known as Broca’s aphasia (aphasia = difficulty with communication). Wernicke’s aphasia also exists, and in this condition, a patient will struggle to understand what is being said to them and chooses to respond with inappropriate words in conversation. In this condition, they are unaware of their inability to understand and choose appropriate language.",
                Popup2Title = "Research Note: Sleep",
                Popup2Content = "Sleep is often measured using cortical activity levels. Electrodes are placed on the skull in a procedure known as an electroencephalogram (EEG) and the action potentials of cortical neurons are measured. During a particular phase of the sleep cycle, called rapid eye movement sleep (REM) sleep, there can be more cortical activity than when we are awake!",
                Popup3Title = "Revision Note: Simplify",
                Popup3Content = "Chances are you have a lot of revision to do for your exams, and the cerebral cortex only makes up a small part of that. So, let’s simplify the content here even further, as a first step in memorising the cerebral cortex… Everything in front of the central sulcus (see Figure 2.7.1.) is about doing things (e.g. the primary motor cortex enables movement and the prefrontal cortex enables decision-making) and everything behind the central sulcus is about experiencing things (e.g. the primary somatosensory cortex is about bodily sensations and the primary visual cortex is about seeing things). And that’s it!",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section28",
                Title = "2.8. Limbic System",
                Subtitle1 = "The Limbic System",
                Description1 = "The limbic system is a group of cortical and subcortical structures in the brain that are interlinked and is responsible for the following functions:<br/><ul><li>Linking memories to the motivations behind our behaviours</li><li>Linking behaviours to our body-wide homeostatic state</li><li>Adding emotional context to events in our lives</li></ul><br/>",
                Subtitle2 = "Functions of the hippocampus",
                Description2 = "Sometimes brain regions are classified by their structure or embryonic origin. In contrasts to this, the limbic system contains brain regions that are largely linked by function. So, for example: the hippocampus, which is structurally part of the temporal lobe, is actually functionally part of the limbic system. Just something to be aware of! The following structures can be considered part of the limbic system and are shown in Figure 2.8.1:<br/><ul><li><b>Hippocampus</b></li><li><b>Amygdala</b></li><li><b>Cingulate gyrus</b></li><li><b>Association cortices</b></li><li><b>Fornix</b></li><li><b>Hypothalamus</b></li><li><b>Thalamus</b></li>",
                Subtitle3 = "The Limbic System Pathway",
                Description3 = "The neuronal links between the structures and functions of the limbic system allow us to generate a map of the processes that ultimately decide our complex behaviours. This is described below and shown as a flowchart in Figure 2.8.2.<br/><br/>The association cortices of the cerebral cortex receive action potentials as a result of a stimulus. For this example, let’s imagine that the stimulus is a huge plate of fries. The association cortices provide detail and context to the stimulus. So, in our example, the visual association cortex helps us to determine that we are indeed looking at a plate of fries, and not similarly shaped or coloured food that we are also familiar with. The sensory association cortex may also register the temperature of the plate that the fries are on as we carry it.<br/><br/>The association area then sends action potentials to the hippocampus or the amygdala. The hippocampus allows us to remember events and situations that we have personally experienced – this capacity is termed ‘episodic memory’. So, we might remember watching a funny movie with our friends while eating fries, and this positive memory is attached to the stimulus. The amygdala might also receive action potentials and, because it is concerned with instinctive motivational behaviours, it recognises that we are hungry and need to eat. The hippocampus and amygdala then send action potentials to both the hypothalamus and the basal ganglia. The hypothalamus will induce autonomic nervous and endocrine (hormonal) responses to stimulate appetite, while the basal ganglia will contribute to the motor activities involved in actually eating the fries, for example hand and arm movements.",
                ImageUri1 = "limbicstructures.png",
                ImageUri2 = "limbicpathway.png",

                Popup1Title = "Clinical Note: Epilepsy",
                Popup1Content = @"Some patients with severe temporal lobe epilepsy, that is poorly controlled with anti-epileptic medications, are offered a procedure called an amygdalohippocampectomy. This involves the surgical removal, or resection, of the amygdala and hippocampus. You can read more about the procedure <a href=""http://emedicine.medscape.com/article/1874484-overview"">here</a>.",
                Popup2Title = "Research Note: Ablative Surgery of the Limbic System",
                Popup2Content = @"<a href=""https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6863509/"">This</a> research article discusses ablative surgery of the limbic system, i.e. surgery that destroys parts of the limbic system in order to reduce the symptoms of psychiatric diseases, such as major depressive disorder and obsessive compulsive disorder (OCD). One of the targets of this surgery is the anterior cingulate cortex. The article (by Sinha et al., 2015) also examines the idea that there are 'predictors' of who will respond best to this type of treatment.",
                Popup3Title = "Revision Note: Flow Charts",
                Popup3Content = "Sometimes sketching out flow charts can provide an excellent way to visualise processes and mechanisms, without having to draw out the complex anatomy of the brain. They are also great for understanding arterial layout and blood flow. Colouring in the sketches can also help them remain brighter in your hippocampus/memory!",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section29",
                Title = "2.9. The HPA Axis",
                Subtitle1 = "Overview of the HPA Axis",
                Description1 = "The HPA axis is the abbreviation for the hypothalamic-pituitary-adrenal axis. It is a circuit than runs between the hypothalamus, the pituitary gland, and the adrenal glands on top of the kidneys. These structures communicate with each other using a variety of hormones. Overall, the HPA axis is vital to the regulation of the homeostatic state of the body. For example, the HPA in part regulates metabolism by affecting the action of the thyroid hormones and cortisol. Let’s take a look at the various parts of the HPA axis and see how they communicate with each other.",
                Subtitle2 = "From the Hypothalamus to the Pituitary Gland",
                Description2 = "The hypothalamus and pituitary gland are parts of the diencephalon (see Section 2.1. Overview of the Brain). The hypothalamus has lots of nuclei that are responsible for producing ‘releasing’ hormones. These ‘releasing’ hormones then travel a short distance through a portal system of blood vessels to the pituitary gland. To help understand this better, let’s take an example. Corticotropin releasing hormone (CRH) is secreted from the hypothalamus and flows into the anterior pituitary gland. When CRH arrives here, it stimulates the secretion of another hormone, called adrenocorticotropic hormone (ACTH), into the main circulation.",
                Subtitle3 = "From the Pituitary Gland to the Adrenal Cortex",
                Description3 = "ACTH travels in the main circulation to the adrenal glands (sometimes these are called the suprarenal glands). There are two parts to the adrenal glands – the outer cortex and the inner medulla. ACTH arrives here and stimulates the production of a steroid hormone called cortisol. Cortisol then flows into the main circulation and is responsible for a number of body-wide effects, including increasing blood pressure, increasing blood glucose and increasing blood amino acid levels. But why would we need these body-wide effects? Well, cortisol is a ‘stress hormone’ that is secreted in response to fight or flight situations, trauma and infection. In these instances, the body wants to increase the blood pressure and the amount of glucose available for respiration to ensure survival. One way to increase blood glucose is to make glucose from amino acids in the liver – this process is called gluconeogenesis.<br/><br/>Once the cortisol has circulated and the blood pressure has been increased, etc, negative feedback takes effect. This means that the hypothalamus detects the increased cortisol level and, as a result, stops producing CRH, and therefore the adrenal glands stop producing cortisol. Now everything has returned to its default level.<br/><br/>Other hormones that are secreted by the anterior pituitary in response to activity in the hypothalamus include:<br/><ul><li>Thyroid stimulating hormone</li><li>Growth hormone</li><li>Prolactin</li><li>Gonadotropes (i.e. FSH and LH which regulate ovulation)</li></ul><br/>",
                ImageUri1 = "hpaaxis.png",
                ImageUri2 = "cortisol.png",

                Popup1Title = "Clinical Note: Pituitary Tumour",
                Popup1Content = "A pituitary tumour, or adenoma, is a tumour that grows on the pituitary gland. It is usually benign (non-cancerous) and classed as either ‘functional’ or ‘non-functional’. A functional pituitary tumour arises from the hormone-producing cells of the pituitary gland and will secrete an excess amount of a particular pituitary hormone (e.g. a prolactinoma secretes excess prolactin), whereas a non-functional pituitary tumour has no effect on hormone secretion. Diagnosis is through blood tests and brain scans, and treatment can involve medication or endoscopic surgery through the nose.",
                Popup2Title = "Research Note: Chronic Fatigue Syndrome (CFS) and HPA Axis Dysfunction",
                Popup2Content = @"CFS is a neurological condition with symptoms of extreme tiredness, poor memory and concentration, and an upset sleeping pattern. Research has shown that a large proportion of people with CFS also display dysfunction of the HPA axis which, as we know, is vital for regulating blood pressure, blood glucose and metabolism among other things. At this stage, researchers do not know whether CFS causes HPA axis dysfunction or HPA axis dysfunction causes CFS, of if there is even a relationship between the two, but <a href=""https://www.hindawi.com/journals/isrn/2013/784520/"">here</a> is an interesting review on the topic by Tomas, Newton and Watson from Newcastle University (2013).",
                Popup3Title = "Revision Note: Thyroid Hormones",
                Popup3Content = "The regulation of thyroid hormones by the HPA axis is very similar to cortisol regulation. Thyrotropin-releasing hormone (TRH) is secreted from the hypothalamus. It reaches the anterior pituitary and stimulates the release of thyroid-stimulating hormone (TSH). TSH then enters the main circulation and travels to the thyroid gland in the neck. Here, TSH stimulates the release of thyroxine, which then enters the main circulation and influences the body’s metabolic rate. Negative feedback also ensures thyroxine levels are returned to normal when appropriate.",

            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section210",
                Title = "2.10. Deeper Dive: Dural Venous Sinuses",
                Subtitle1 = "What is a Deeper Dive?",
                Description1 = "I am an anatomist by training and these ‘Deeper Dives’ are designed to give you a more in-depth look at the anatomy of a particular region that is related to neuroscience. This isn’t introductory stuff – it’s pretty detailed, so if you’re only starting out on learning neuroanatomy/neuroscience, this might be over-the-top – still good background reading though!</p><p>Dural venous sinuses are spaces in the cranial cavity through which venous blood drains. They receive blood from:<br/><ul><li>Emissary veins – these veins connect superficial veins in the scalp with the veins and sinuses inside the cranial cavity.</li>  <li>Diploic veins – these veins drain the diploe, which is the space in-between the two layers of compact bone that make up the calvarium (skullcap).</li><li>Cerebral veins – these veins drain the cerebral hemispheres.</li></ul><br/>",
                Subtitle2 = "The Main Dural Venous Sinuses",
                Description2 = "<p>The main dural venous sinuses are as follows:</p><br/><ul>  <li>Confluence of sinuses – this is where many of the sinuses meet; it lies deep to the occipital protuberance, which you can palpate in the midline of the occipital bone).</li>  <li>Superior sagittal sinus (in the superior portion of the falx cerebri).</li>  <li>Inferior sagittal sinus (in the inferior portion of the falx cerebri).</li>  <li>Transverse sinuses (left and right, in the tentorium cerebelli).</li>  <li>Straight sinus (connects the inferior sagittal sinus with the left transverse sinus).</li>  <li>Sigmoidal sinuses (left and right), which drain the transverse sinuses; these also become continuous with the internal jugular veins on each side.</li>  <li>Occipital sinus, which drains upwards along the centre of the internal aspect of the occipital bone to enter the confluence of sinuses.</li>  <li>Sphenoparietal sinuses (left and right), which drains along the lesser wing of the sphenoid bone into the cavernous sinuses.</li>  <li>Cavernous sinuses (left and right), which are chunky squarish spaces that sit at the sides of the pituitary fossa and body of the sphenoid.</li></ul><br/><p>There are also superior and inferior petrosal sinuses (left and right) but I have omitted these for brevity as the list above is already quite long!</p>",
                Subtitle3 = "Typical Courses",
                Description3 = "<p>The typical course for blood in these sinuses is as follows:</p><br/><ul>  <li>Cortical veins, superior sagittal sinus, confluence of sinuses, right transverse sinus, right sigmoidal sinus and finally the right internal jugular vein.</li>  <li>Great cerebral vein/vein of Galen, Inferior sagittal sinus, straight sinus, confluence of sinuses, left transverse sinus, left sigmoidal sinus and finally the left internal jugular vein.</li>  <li>Left/right sphenoparietal sinus, left/right cavernous sinus, left/right inferior petrosal sinus, left/right transverse sinus, left/right sigmoidal sinus and finally the left/right internal jugular vein.*</li></ul><br/><p>Note that the cavernous sinus also drains via the superior petrosal sinuses, the venous plexuses of the internal carotid artery and potentially superior ophthalmic veins.</p>",
                ImageUri1 = "dvsedited.png",
                ImageUri2 = null,

                Popup1Title = "",
                Popup1Content = "",
                Popup2Title = "",
                Popup2Content = "",
                Popup3Title = "",
                Popup3Content = "",
            });
            SubsectionList.Add(new SubsectionModel
            {
                PageId = "section211",
                Title = "2.11. The Cerebellum",
                Subtitle1 = "Overview",
                Description1 = "As discussed in Section 2.1., the cerebellum is a hindbrain structure. Embryologically, it develops from the rhombencephalon, then the metencephalon, which then separates into the pons and cerebellum.<br/><br/>The cerebellum’s main role is to modify motor signals that come from the motor cortex so that the contractions of the body’s muscles are smooth, coordinated and as intended. The cerebellum does this ‘refinement’ by integrating sound, vision, proprioception and balance into the descending motor signals; the cerebellum then sends the motor signals back up to the primary cortex, and from here they will travel down the spinal cord and to the muscles (shown in Figure 2.11.2.).",
                Subtitle2 = "Anatomy",
                Description2 = "<b>Anatomy</b><br/>The cerebellum has three anatomical divisions, called lobes (these are shown in Figure 2.11.1).:<ul><li>Anterior lobe</li><li>Posterior lobe</li><li>Flocculonodular lobe</li></ul>The cerebellum can also be said to have three different anatomical divisions:<ul><li>Vermis (the median portion)</li><li>Paravermis (the medial portions)</li><li>Lateral zones (the most lateral portions – mainly made up of the cerebellar hemispheres)</li></ul>On top of this… functionally, the cerebellum has three divisions:<ul><li>Vestibulocerebellum – coordinates balance, sound and wakefulness</li><li>Spinocerebellum – coordinates upper limb movements</li><li>Cerebrocerebellum (also called the neocerebellum) – coordinates lower and trunk limb movements</li></ul>",
                Subtitle3 = "Physiology",
                Description3 = "<b>Physiology</b><br/>The cerebellar pathways are complex, but they can be simplified into three sequential stages which you can read about below.<br/><br/><b>Stage 1</b><br/>There are two fibre types that enter the cerebellum (i.e. are afferent fibres) – these are the climbing and mossy fibres that carry proprioceptive, vestibular/balance, auditory and visual information into the cerebellar cortex (by the way, the cerebellar cortex is totally different to the cerebral cortex!) Both the climbing and mossy fibres are excitatory, and they have multiple connections, the first of which arises just as the fibres enter the cerebellar cortex and the connection is with the deep cerebellar nuclei. So, the climbing and mossy fibres excite the deep cerebellar nuclei which send signals to the motor cortices.<br/><br/><b>Stage 2</b><br/>Remember I said that the climbing and mossy fibres have multiple connections? Well, the second set of connections is with inhibitory Purkinje cells in the cerebellar cortex. These Purkinje cells then go on to have connections with the deep cerebellar nuclei, which they inhibit. This stage 2 pathway takes a little longer to operate than the stage 1 pathway mentioned earlier. So, the combined effects of stages 1 and 2 are initial excitation followed by inhibition. Now onto stage 3…<br/><br/><b>Stage 3</b><br/>Another type of cell in the cerebellar cortex, the Golgi cell, inhibits the mossy fibres going to the Purkinje cells. When this happens, the Purkinje cells are inhibited from inhibiting the deep cerebellar nuclei (this is called disinhibition, meaning the deep cerebellar nuclei can send out excitatory signals). This stage 3 pathway takes even longer to operate than the stage 1 and 2 pathways. So, the combined effect of all three pathways is now excitation, then inhibition, then disinhibition (aka excitation).<br/><br/>So, in conclusion, most of the output from the cerebellum is excitatory to the motor cortices.",
                ImageUri1 = "cerebellum1.png",
                ImageUri2 = "cerebellum2.png",

                Popup1Title = "Clinical Note: Cerebellar Ataxia",
                Popup1Content = "Cerebellar ataxia is a collection of abnormal movement signs and symptoms that develop when the cerebellum is not working properly, for example, due to a tumour, bleed in the back part of the floor of the skull (called the posterior cranial fossa), problem alcohol use or multiple sclerosis. Cerebellar ataxia has three primary symptoms: unsteady gait, poor muscle coordination and uncontrolled eye movements. Dysarthria can also be a symptom of cerebellar ataxia – the term ‘dysarthria’ means individuals have difficulty controlling the muscles that they use to speak and swallow.",
                Popup2Title = "",
                Popup2Content = "",
                Popup3Title = "",
                Popup3Content = "",
            });
        }
    }
}
